################################################################################
# roOs Makefile
#
# Created: 23/05/2020
#
# Author: Alexy Torres Aurora Dugo
#
# Application module makefile. This makefile is used to compile the a program
# for roOs.
################################################################################

# Dependencies
include dependencies.mk
include ../../../ARTIFACTS/settings.mk

BINARY_NAME = init

rwildcard=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2))

# Variables definitions
SRC_DIR    = src
BUILD_DIR  = build
LIB_DIR    = lib
INC_DIR    = includes
BIN_DIR    = bin
ARTIFACTS_DIR = ../../../ARTIFACTS

C_SRCS = $(call rwildcard,$(SRC_DIR),*.c)
A_SRCS = $(call rwildcard,$(SRC_DIR),*.s)
C_OBJS = $(C_SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
A_OBJS = $(A_SRCS:$(SRC_DIR)/%.s=$(BUILD_DIR)/%.o)

.PHONY: all
all: init module

init:
	@echo "\e[1m\e[34m\n#-------------------------------------------------------------------------------\e[22m\e[39m"
	@echo "\e[1m\e[34m| Compiling program $(BINARY_NAME)\e[22m\e[39m"
	@echo "\e[1m\e[34m#-------------------------------------------------------------------------------\n\e[22m\e[39m"

	@mkdir -p $(BUILD_DIR)
	@mkdir -p $(BIN_DIR)

module: compile_asm compile_cc

	$(LD) $(LDFLAGS) -T $(ARTIFACTS_DIR)/$(USER_LINKER_FILE) $(BUILD_DIR)/*.o -o $(BIN_DIR)/$(BINARY_NAME) $(DEP_MODULES) $(DEP_LIBS) -Map=$(BUILD_DIR)/output.map
	@echo "\e[1m\e[92m=> Generated program $(BINARY_NAME)\e[22m\e[39m"
	@echo "\e[1m\e[92m--------------------------------------------------------------------------------\n\e[22m\e[39m"

# Assembly sources compilation
compile_asm: $(A_OBJS)
	@echo "\e[1m\e[94m=> Compiled ASM sources\e[22m\e[39m"
	@echo

# C sources compilation
compile_cc: $(C_OBJS)
	@echo "\e[1m\e[94m=> Compiled C sources\e[22m\e[39m"
	@echo

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
ifeq ($(DEBUG), TRUE)
	@echo -n "  DEBUG "
endif
	@echo  "\e[32m  $< \e[22m\e[39m=> \e[1m\e[94m$@\e[22m\e[39m"
	$(CC) $(CFLAGS) $< -o $@ -I $(INC_DIR) $(DEP_INCLUDES)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.S
	@echo  "\e[32m  $< \e[22m\e[39m=> \e[1m\e[94m$@\e[22m\e[39m"
	$(AS) $(ASFLAGS) $< -o $@ -I $(INC_DIR) $(DEP_INCLUDES)

# Clean
clean:
	$(RM) -rf $(BUILD_DIR) $(BIN_DIR)
	@echo "\e[1m\e[34m\n#-------------------------------------------------------------------------------\e[22m\e[39m"
	@echo "\e[1m\e[34m| Cleaned program $(BINARY_NAME)\e[22m\e[39m"
	@echo "\e[1m\e[34m#-------------------------------------------------------------------------------\n\e[22m\e[39m"

# Check header files modifications
-include $(C_OBJS:.o=.d)